#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siggo.SIGC.DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SiggoData")]
	public partial class DADeclaracionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DADeclaracionDataContext() : 
				base(global::Siggo.SIGC.DataAccess.Properties.Settings.Default.SiggoDataConnectionString5, mappingSource)
		{
			OnCreated();
		}
		
		public DADeclaracionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DADeclaracionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DADeclaracionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DADeclaracionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_LISTAR_DECLARACIONES_DOCUMENTOS")]
		public ISingleResult<SP_LISTAR_DECLARACIONES_DOCUMENTOSResult> SP_LISTAR_DECLARACIONES_DOCUMENTOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdEmpresa", DbType="VarChar(5)")] string idEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdRegistro", DbType="Int")] System.Nullable<int> idRegistro)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idEmpresa, idRegistro);
			return ((ISingleResult<SP_LISTAR_DECLARACIONES_DOCUMENTOSResult>)(result.ReturnValue));
		}

        [global::System.Data.Linq.Mapping.FunctionAttribute(Name = "dbo.SP_UPD_DOCUMENTACION_MENSUAL")]
        public int SP_UPD_DOCUMENTACION_MENSUAL([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "IdEmpresa", DbType = "VarChar(5)")] string idEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "IdRegistro", DbType = "Int")] System.Nullable<int> idRegistro, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "NroSecuencia", DbType = "Int")] System.Nullable<int> nroSecuencia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "FechaPresentacion", DbType = "DateTime")] System.Nullable<System.DateTime> fechaPresentacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "Detalle", DbType = "VarChar(200)")] string detalle, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "NombreArchivo", DbType = "VarChar(200)")] string nombreArchivo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "PesoKb", DbType = "Int")] System.Nullable<int> pesoKb, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "RegistradoPor", DbType = "VarChar(10)")] string registradoPor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "RETURN_VALUE", DbType = "Bit")] ref System.Nullable<bool> RETURN_VALUE)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idEmpresa, idRegistro, nroSecuencia, fechaPresentacion, detalle, nombreArchivo, pesoKb, registradoPor, RETURN_VALUE);
            RETURN_VALUE = ((System.Nullable<bool>)(result.GetParameterValue(8)));
            return ((int)(result.ReturnValue));
        }

        [global::System.Data.Linq.Mapping.FunctionAttribute(Name = "dbo.SP_UPD_DOCUMENTACIONDATO_MENSUAL")]
        public int SP_UPD_DOCUMENTACIONDATO_MENSUAL([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "IdEmpresa", DbType = "VarChar(5)")] string idEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "IdRegistro", DbType = "Int")] System.Nullable<int> idRegistro, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "NroSecuencia", DbType = "Int")] System.Nullable<int> nroSecuencia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "IdDato", DbType = "Int")] System.Nullable<int> idDato, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "VarChar(250)")] string ls_valor_texto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] System.Nullable<int> ln_valor_entero, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Decimal(14,2)")] System.Nullable<decimal> ldc_valor_decimal, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "DateTime")] System.Nullable<System.DateTime> dt_valor_fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Bit")] System.Nullable<bool> bt_valor_bool, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "RegistradoPor", DbType = "VarChar(10)")] string registradoPor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "RETURN_VALUE", DbType = "Bit")] ref System.Nullable<bool> RETURN_VALUE)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idEmpresa, idRegistro, nroSecuencia, idDato, ls_valor_texto, ln_valor_entero, ldc_valor_decimal, dt_valor_fecha, bt_valor_bool, registradoPor, RETURN_VALUE);
            RETURN_VALUE = ((System.Nullable<bool>)(result.GetParameterValue(10)));
            return ((int)(result.ReturnValue));
        }

        [global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_LISTAR_DECLARACIONES")]
		public ISingleResult<SP_LISTAR_DECLARACIONESResult> SP_LISTAR_DECLARACIONES([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NroOrden", DbType="VarChar(10)")] string nroOrden, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contratista", DbType="VarChar(5)")] string contratista, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cliente", DbType="VarChar(5)")] string cliente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mes", DbType="Char(2)")] string mes, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Anho", DbType="Char(4)")] string anho, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipoRecurso", DbType="VarChar(5)")] string tipoRecurso, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="VarChar(10)")] string idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdRegistro", DbType="VarChar(10)")] string idRegistro, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado", DbType="VarChar(1)")] string estado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> nPag, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> nNumxPag)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nroOrden, contratista, cliente, mes, anho, tipoRecurso, idUsuario, idRegistro, estado, nPag, nNumxPag);
			return ((ISingleResult<SP_LISTAR_DECLARACIONESResult>)(result.ReturnValue));
		}
	}
	
	public partial class SP_LISTAR_DECLARACIONES_DOCUMENTOSResult
	{
		
		private string _IdEmpresa;
		
		private System.Nullable<int> _IdRegistro;
		
		private System.Nullable<int> _NroSecuencia;
		
		private System.Nullable<int> _IdTipoServicio;
		
		private string _TipoServicio;
		
		private System.Nullable<int> _IdTipoDocumento;
		
		private string _NivelRiesgo;
		
		private string _DescripcionArchivo;
		
		private string _Frecuencia;
		
		private string _Estado;
		
		private string _FechaDocumento;
		
		private string _FechaVencimiento;
		
		private string _IdImagen;
		
		private string _Evidencia;
		
		private string _Detalle;
		
		public SP_LISTAR_DECLARACIONES_DOCUMENTOSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEmpresa", DbType="VarChar(5)")]
		public string IdEmpresa
		{
			get
			{
				return this._IdEmpresa;
			}
			set
			{
				if ((this._IdEmpresa != value))
				{
					this._IdEmpresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRegistro", DbType="Int")]
		public System.Nullable<int> IdRegistro
		{
			get
			{
				return this._IdRegistro;
			}
			set
			{
				if ((this._IdRegistro != value))
				{
					this._IdRegistro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NroSecuencia", DbType="Int")]
		public System.Nullable<int> NroSecuencia
		{
			get
			{
				return this._NroSecuencia;
			}
			set
			{
				if ((this._NroSecuencia != value))
				{
					this._NroSecuencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoServicio", DbType="Int")]
		public System.Nullable<int> IdTipoServicio
		{
			get
			{
				return this._IdTipoServicio;
			}
			set
			{
				if ((this._IdTipoServicio != value))
				{
					this._IdTipoServicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoServicio", DbType="VarChar(50)")]
		public string TipoServicio
		{
			get
			{
				return this._TipoServicio;
			}
			set
			{
				if ((this._TipoServicio != value))
				{
					this._TipoServicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoDocumento", DbType="Int")]
		public System.Nullable<int> IdTipoDocumento
		{
			get
			{
				return this._IdTipoDocumento;
			}
			set
			{
				if ((this._IdTipoDocumento != value))
				{
					this._IdTipoDocumento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NivelRiesgo", DbType="VarChar(20)")]
		public string NivelRiesgo
		{
			get
			{
				return this._NivelRiesgo;
			}
			set
			{
				if ((this._NivelRiesgo != value))
				{
					this._NivelRiesgo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescripcionArchivo", DbType="VarChar(100)")]
		public string DescripcionArchivo
		{
			get
			{
				return this._DescripcionArchivo;
			}
			set
			{
				if ((this._DescripcionArchivo != value))
				{
					this._DescripcionArchivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Frecuencia", DbType="VarChar(30)")]
		public string Frecuencia
		{
			get
			{
				return this._Frecuencia;
			}
			set
			{
				if ((this._Frecuencia != value))
				{
					this._Frecuencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(10)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaDocumento", DbType="VarChar(10)")]
		public string FechaDocumento
		{
			get
			{
				return this._FechaDocumento;
			}
			set
			{
				if ((this._FechaDocumento != value))
				{
					this._FechaDocumento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaVencimiento", DbType="VarChar(10)")]
		public string FechaVencimiento
		{
			get
			{
				return this._FechaVencimiento;
			}
			set
			{
				if ((this._FechaVencimiento != value))
				{
					this._FechaVencimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdImagen", DbType="VarChar(10)")]
		public string IdImagen
		{
			get
			{
				return this._IdImagen;
			}
			set
			{
				if ((this._IdImagen != value))
				{
					this._IdImagen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Evidencia", DbType="VarChar(5)")]
		public string Evidencia
		{
			get
			{
				return this._Evidencia;
			}
			set
			{
				if ((this._Evidencia != value))
				{
					this._Evidencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detalle", DbType="VarChar(100)")]
		public string Detalle
		{
			get
			{
				return this._Detalle;
			}
			set
			{
				if ((this._Detalle != value))
				{
					this._Detalle = value;
				}
			}
		}
	}
	
	public partial class SP_LISTAR_DECLARACIONESResult
	{
		
		private string _IdEmpresa;
		
		private System.Nullable<int> _IdRegistro;
		
		private string _Empresa;
		
		private string _IdRecurso;
		
		private string _Recurso;
		
		private string _NroReferenciaRecurso;
		
		private string _Estado;
		
		private System.Nullable<int> _NUMREG;
		
		private System.Nullable<decimal> _TOTPAG;
		
		private System.Nullable<long> _TOTREG;
		
		public SP_LISTAR_DECLARACIONESResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEmpresa", DbType="VarChar(5)")]
		public string IdEmpresa
		{
			get
			{
				return this._IdEmpresa;
			}
			set
			{
				if ((this._IdEmpresa != value))
				{
					this._IdEmpresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRegistro", DbType="Int")]
		public System.Nullable<int> IdRegistro
		{
			get
			{
				return this._IdRegistro;
			}
			set
			{
				if ((this._IdRegistro != value))
				{
					this._IdRegistro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Empresa", DbType="VarChar(50)")]
		public string Empresa
		{
			get
			{
				return this._Empresa;
			}
			set
			{
				if ((this._Empresa != value))
				{
					this._Empresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRecurso", DbType="VarChar(5)")]
		public string IdRecurso
		{
			get
			{
				return this._IdRecurso;
			}
			set
			{
				if ((this._IdRecurso != value))
				{
					this._IdRecurso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Recurso", DbType="VarChar(200)")]
		public string Recurso
		{
			get
			{
				return this._Recurso;
			}
			set
			{
				if ((this._Recurso != value))
				{
					this._Recurso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NroReferenciaRecurso", DbType="VarChar(30)")]
		public string NroReferenciaRecurso
		{
			get
			{
				return this._NroReferenciaRecurso;
			}
			set
			{
				if ((this._NroReferenciaRecurso != value))
				{
					this._NroReferenciaRecurso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(20)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUMREG", DbType="Int")]
		public System.Nullable<int> NUMREG
		{
			get
			{
				return this._NUMREG;
			}
			set
			{
				if ((this._NUMREG != value))
				{
					this._NUMREG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTPAG", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> TOTPAG
		{
			get
			{
				return this._TOTPAG;
			}
			set
			{
				if ((this._TOTPAG != value))
				{
					this._TOTPAG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTREG", DbType="BigInt")]
		public System.Nullable<long> TOTREG
		{
			get
			{
				return this._TOTREG;
			}
			set
			{
				if ((this._TOTREG != value))
				{
					this._TOTREG = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
