#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siggo.SIGC.DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SiggoData")]
	public partial class DAEmpresaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DAEmpresaDataContext() : 
				base(global::Siggo.SIGC.DataAccess.Properties.Settings.Default.SiggoDataConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public DAEmpresaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DAEmpresaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DAEmpresaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DAEmpresaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_MANT_REG_EMPRESA")]
		public int SP_MANT_REG_EMPRESA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Opcion", DbType="Int")] System.Nullable<int> opcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdEmpresa", DbType="VarChar(5)")] string idEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RazonSocial", DbType="VarChar(50)")] string razonSocial, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="VarChar(50)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PrefijoCorreo", DbType="VarChar(30)")] string prefijoCorreo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="VarChar(10)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correo", DbType="VarChar(200)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contacto", DbType="VarChar(200)")] string contacto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipoEmpresa", DbType="VarChar(10)")] string tipoEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RucEmpresa", DbType="VarChar(20)")] string rucEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiasNotificacionVencimiento", DbType="Int")] System.Nullable<int> diasNotificacionVencimiento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ActividadNormalEspecifica", DbType="Bit")] System.Nullable<bool> actividadNormalEspecifica, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipoEmpresaSiggo", DbType="VarChar(15)")] string tipoEmpresaSiggo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDCliente", DbType="VarChar(5)")] string iDCliente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RegistradoPor", DbType="VarChar(50)")] string registradoPor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), opcion, idEmpresa, razonSocial, direccion, prefijoCorreo, telefono, correo, contacto, tipoEmpresa, rucEmpresa, diasNotificacionVencimiento, actividadNormalEspecifica, tipoEmpresaSiggo, iDCliente, registradoPor);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_DATOS_EMPRESA")]
		public ISingleResult<SP_OBTENER_DATOS_EMPRESAResult> SP_OBTENER_DATOS_EMPRESA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDEMPRESA", DbType="VarChar(5)")] string iDEMPRESA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDEMPRESA);
			return ((ISingleResult<SP_OBTENER_DATOS_EMPRESAResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_LISTAR_EMPRESAS")]
		public ISingleResult<SP_LISTAR_EMPRESASResult> SP_LISTAR_EMPRESAS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Identificador", DbType="VarChar(5)")] string identificador, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreEmpresa", DbType="VarChar(100)")] string nombreEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipoEmpresa", DbType="VarChar(20)")] string tipoEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipoEmpresaSiggo", DbType="VarChar(30)")] string tipoEmpresaSiggo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDUSUARIO", DbType="VarChar(10)")] string iDUSUARIO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), identificador, nombreEmpresa, tipoEmpresa, tipoEmpresaSiggo, iDUSUARIO);
			return ((ISingleResult<SP_LISTAR_EMPRESASResult>)(result.ReturnValue));
		}
	}
	
	public partial class SP_OBTENER_DATOS_EMPRESAResult
	{
		
		private string _IdEmpresa;
		
		private string _RazonSocial;
		
		private string _Direccion;
		
		private string _PrefijoCorreo;
		
		private string _Telefono;
		
		private string _Correo;
		
		private string _Contacto;
		
		private string _TipoEmpresa;
		
		private string _RucEmpresa;
		
		private int _DiasNotificacionVencimiento;
		
		private bool _ActividadNormalEspecifica;
		
		private string _TipoEmpresaSiggo;
		
		private string _IDCliente;
		
		private char _Estado;
		
		private char _Accion;
		
		private string _FECMAKER;
		
		private string _HoraRegistro;
		
		private string _MAKER;
		
		public SP_OBTENER_DATOS_EMPRESAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEmpresa", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IdEmpresa
		{
			get
			{
				return this._IdEmpresa;
			}
			set
			{
				if ((this._IdEmpresa != value))
				{
					this._IdEmpresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RazonSocial", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string RazonSocial
		{
			get
			{
				return this._RazonSocial;
			}
			set
			{
				if ((this._RazonSocial != value))
				{
					this._RazonSocial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrefijoCorreo", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string PrefijoCorreo
		{
			get
			{
				return this._PrefijoCorreo;
			}
			set
			{
				if ((this._PrefijoCorreo != value))
				{
					this._PrefijoCorreo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this._Correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contacto", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Contacto
		{
			get
			{
				return this._Contacto;
			}
			set
			{
				if ((this._Contacto != value))
				{
					this._Contacto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoEmpresa", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string TipoEmpresa
		{
			get
			{
				return this._TipoEmpresa;
			}
			set
			{
				if ((this._TipoEmpresa != value))
				{
					this._TipoEmpresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RucEmpresa", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string RucEmpresa
		{
			get
			{
				return this._RucEmpresa;
			}
			set
			{
				if ((this._RucEmpresa != value))
				{
					this._RucEmpresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiasNotificacionVencimiento", DbType="Int NOT NULL")]
		public int DiasNotificacionVencimiento
		{
			get
			{
				return this._DiasNotificacionVencimiento;
			}
			set
			{
				if ((this._DiasNotificacionVencimiento != value))
				{
					this._DiasNotificacionVencimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActividadNormalEspecifica", DbType="Bit NOT NULL")]
		public bool ActividadNormalEspecifica
		{
			get
			{
				return this._ActividadNormalEspecifica;
			}
			set
			{
				if ((this._ActividadNormalEspecifica != value))
				{
					this._ActividadNormalEspecifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoEmpresaSiggo", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string TipoEmpresaSiggo
		{
			get
			{
				return this._TipoEmpresaSiggo;
			}
			set
			{
				if ((this._TipoEmpresaSiggo != value))
				{
					this._TipoEmpresaSiggo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCliente", DbType="VarChar(5)")]
		public string IDCliente
		{
			get
			{
				return this._IDCliente;
			}
			set
			{
				if ((this._IDCliente != value))
				{
					this._IDCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Char(1) NOT NULL")]
		public char Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Accion", DbType="Char(1) NOT NULL")]
		public char Accion
		{
			get
			{
				return this._Accion;
			}
			set
			{
				if ((this._Accion != value))
				{
					this._Accion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECMAKER", DbType="VarChar(30)")]
		public string FECMAKER
		{
			get
			{
				return this._FECMAKER;
			}
			set
			{
				if ((this._FECMAKER != value))
				{
					this._FECMAKER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoraRegistro", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string HoraRegistro
		{
			get
			{
				return this._HoraRegistro;
			}
			set
			{
				if ((this._HoraRegistro != value))
				{
					this._HoraRegistro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKER", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MAKER
		{
			get
			{
				return this._MAKER;
			}
			set
			{
				if ((this._MAKER != value))
				{
					this._MAKER = value;
				}
			}
		}
	}
	
	public partial class SP_LISTAR_EMPRESASResult
	{
		
		private string _IDEMPRESA;
		
		private string _RAZONSOCIAL;
		
		private string _DIRECCION;
		
		private string _PREFIJOCORREO;
		
		private string _TELEFONO;
		
		private string _CORREO;
		
		private string _CONTACTO;
		
		private string _TIPOEMPRESA;
		
		private string _DESC_TIPOEMPRESA;
		
		private string _RUCEMPRESA;
		
		private int _DIASNOTIFICACIONVENCIMIENTO;
		
		private bool _ACTIVIDADNORMALESPECIFICA;
		
		private string _TIPOEMPRESASIGGO;
		
		private string _IDCLIENTE;
		
		private string _EmpresaAsociada;
		
		private char _ESTADO;
		
		private char _ACCION;
		
		private System.DateTime _FECHAREGISTRO;
		
		private string _HORAREGISTRO;
		
		private string _REGISTRADOPOR;
		
		public SP_LISTAR_EMPRESASResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDEMPRESA", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IDEMPRESA
		{
			get
			{
				return this._IDEMPRESA;
			}
			set
			{
				if ((this._IDEMPRESA != value))
				{
					this._IDEMPRESA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RAZONSOCIAL", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string RAZONSOCIAL
		{
			get
			{
				return this._RAZONSOCIAL;
			}
			set
			{
				if ((this._RAZONSOCIAL != value))
				{
					this._RAZONSOCIAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRECCION", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DIRECCION
		{
			get
			{
				return this._DIRECCION;
			}
			set
			{
				if ((this._DIRECCION != value))
				{
					this._DIRECCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PREFIJOCORREO", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string PREFIJOCORREO
		{
			get
			{
				return this._PREFIJOCORREO;
			}
			set
			{
				if ((this._PREFIJOCORREO != value))
				{
					this._PREFIJOCORREO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string TELEFONO
		{
			get
			{
				return this._TELEFONO;
			}
			set
			{
				if ((this._TELEFONO != value))
				{
					this._TELEFONO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string CORREO
		{
			get
			{
				return this._CORREO;
			}
			set
			{
				if ((this._CORREO != value))
				{
					this._CORREO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTACTO", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string CONTACTO
		{
			get
			{
				return this._CONTACTO;
			}
			set
			{
				if ((this._CONTACTO != value))
				{
					this._CONTACTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPOEMPRESA", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string TIPOEMPRESA
		{
			get
			{
				return this._TIPOEMPRESA;
			}
			set
			{
				if ((this._TIPOEMPRESA != value))
				{
					this._TIPOEMPRESA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESC_TIPOEMPRESA", DbType="VarChar(100)")]
		public string DESC_TIPOEMPRESA
		{
			get
			{
				return this._DESC_TIPOEMPRESA;
			}
			set
			{
				if ((this._DESC_TIPOEMPRESA != value))
				{
					this._DESC_TIPOEMPRESA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RUCEMPRESA", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string RUCEMPRESA
		{
			get
			{
				return this._RUCEMPRESA;
			}
			set
			{
				if ((this._RUCEMPRESA != value))
				{
					this._RUCEMPRESA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIASNOTIFICACIONVENCIMIENTO", DbType="Int NOT NULL")]
		public int DIASNOTIFICACIONVENCIMIENTO
		{
			get
			{
				return this._DIASNOTIFICACIONVENCIMIENTO;
			}
			set
			{
				if ((this._DIASNOTIFICACIONVENCIMIENTO != value))
				{
					this._DIASNOTIFICACIONVENCIMIENTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACTIVIDADNORMALESPECIFICA", DbType="Bit NOT NULL")]
		public bool ACTIVIDADNORMALESPECIFICA
		{
			get
			{
				return this._ACTIVIDADNORMALESPECIFICA;
			}
			set
			{
				if ((this._ACTIVIDADNORMALESPECIFICA != value))
				{
					this._ACTIVIDADNORMALESPECIFICA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPOEMPRESASIGGO", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string TIPOEMPRESASIGGO
		{
			get
			{
				return this._TIPOEMPRESASIGGO;
			}
			set
			{
				if ((this._TIPOEMPRESASIGGO != value))
				{
					this._TIPOEMPRESASIGGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCLIENTE", DbType="VarChar(5)")]
		public string IDCLIENTE
		{
			get
			{
				return this._IDCLIENTE;
			}
			set
			{
				if ((this._IDCLIENTE != value))
				{
					this._IDCLIENTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpresaAsociada", DbType="VarChar(50)")]
		public string EmpresaAsociada
		{
			get
			{
				return this._EmpresaAsociada;
			}
			set
			{
				if ((this._EmpresaAsociada != value))
				{
					this._EmpresaAsociada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="Char(1) NOT NULL")]
		public char ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCION", DbType="Char(1) NOT NULL")]
		public char ACCION
		{
			get
			{
				return this._ACCION;
			}
			set
			{
				if ((this._ACCION != value))
				{
					this._ACCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHAREGISTRO", DbType="DateTime NOT NULL")]
		public System.DateTime FECHAREGISTRO
		{
			get
			{
				return this._FECHAREGISTRO;
			}
			set
			{
				if ((this._FECHAREGISTRO != value))
				{
					this._FECHAREGISTRO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HORAREGISTRO", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string HORAREGISTRO
		{
			get
			{
				return this._HORAREGISTRO;
			}
			set
			{
				if ((this._HORAREGISTRO != value))
				{
					this._HORAREGISTRO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REGISTRADOPOR", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string REGISTRADOPOR
		{
			get
			{
				return this._REGISTRADOPOR;
			}
			set
			{
				if ((this._REGISTRADOPOR != value))
				{
					this._REGISTRADOPOR = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
