#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siggo.SIGC.DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SiggoData")]
	public partial class DAOrdenServicioDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DAOrdenServicioDataContext() : 
				base(global::Siggo.SIGC.DataAccess.Properties.Settings.Default.SiggoDataConnectionString3, mappingSource)
		{
			OnCreated();
		}
		
		public DAOrdenServicioDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DAOrdenServicioDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DAOrdenServicioDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DAOrdenServicioDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_LISTAR_CONTRATAS")]
		public ISingleResult<SP_LISTAR_CONTRATASResult> SP_LISTAR_CONTRATAS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Identificador", DbType="VarChar(5)")] string identificador, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDUSUARIO", DbType="VarChar(10)")] string iDUSUARIO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), identificador, iDUSUARIO);
			return ((ISingleResult<SP_LISTAR_CONTRATASResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_LISTAR_ORDENES")]
		public ISingleResult<SP_LISTAR_ORDENESResult> SP_LISTAR_ORDENES([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Filtro", DbType="Int")] System.Nullable<int> filtro, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdEmpresa", DbType="VarChar(5)")] string idEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="VarChar(10)")] string idUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), filtro, idEmpresa, idUsuario);
			return ((ISingleResult<SP_LISTAR_ORDENESResult>)(result.ReturnValue));
		}

        [global::System.Data.Linq.Mapping.FunctionAttribute(Name = "dbo.SP_MANT_REG_ORDEN_SERVICIO_AREAS")]
        public int SP_MANT_REG_ORDEN_SERVICIO_AREAS([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "Opcion", DbType = "Int")] System.Nullable<int> opcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "IdEmpresa", DbType = "VarChar(5)")] string idEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "NroOrden", DbType = "Char(10)")] string nroOrden, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CodigoDpto", DbType = "VarChar(10)")] string codigoDpto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "NombreDpto", DbType = "VarChar(30)")] string nombreDpto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "RETURN_VALUE", DbType = "Bit")] ref System.Nullable<bool> RETURN_VALUE)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), opcion, idEmpresa, nroOrden, codigoDpto, nombreDpto, RETURN_VALUE);
            RETURN_VALUE = ((System.Nullable<bool>)(result.GetParameterValue(5)));
            return ((int)(result.ReturnValue));
        }

        [global::System.Data.Linq.Mapping.FunctionAttribute(Name = "dbo.SP_MANT_REG_ORDEN_SERVICIO_CONTRATAS")]
        public int SP_MANT_REG_ORDEN_SERVICIO_CONTRATAS([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "Opcion", DbType = "Int")] System.Nullable<int> opcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "IdEmpresa", DbType = "VarChar(5)")] string idEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "NroOrden", DbType = "Char(10)")] string nroOrden, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "IdContrata", DbType = "VarChar(5)")] string idContrata, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "IdSubContrata", DbType = "VarChar(5)")] string idSubContrata, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "RETURN_VALUE", DbType = "Bit")] ref System.Nullable<bool> RETURN_VALUE)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), opcion, idEmpresa, nroOrden, idContrata, idSubContrata, RETURN_VALUE);
            RETURN_VALUE = ((System.Nullable<bool>)(result.GetParameterValue(5)));
            return ((int)(result.ReturnValue));
        }

        [global::System.Data.Linq.Mapping.FunctionAttribute(Name = "dbo.SP_MANT_REG_ORDEN_SERVICIO_LOCALIZACION")]
        public int SP_MANT_REG_ORDEN_SERVICIO_LOCALIZACION([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "Opcion", DbType = "Int")] System.Nullable<int> opcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "IdEmpresa", DbType = "VarChar(5)")] string idEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "NroOrden", DbType = "Char(10)")] string nroOrden, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "CodigoSede", DbType = "VarChar(10)")] string codigoSede, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "DescripcionSede", DbType = "VarChar(30)")] string descripcionSede, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "RETURN_VALUE", DbType = "Bit")] ref System.Nullable<bool> RETURN_VALUE)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), opcion, idEmpresa, nroOrden, codigoSede, descripcionSede, RETURN_VALUE);
            RETURN_VALUE = ((System.Nullable<bool>)(result.GetParameterValue(5)));
            return ((int)(result.ReturnValue));
        }

        [global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_DATOS_ORDEN_SERVICIO")]
		public ISingleResult<SP_OBTENER_DATOS_ORDEN_SERVICIOResult> SP_OBTENER_DATOS_ORDEN_SERVICIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDEMPRESA", DbType="VarChar(5)")] string iDEMPRESA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NROORDEN", DbType="VarChar(10)")] string nROORDEN)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDEMPRESA, nROORDEN);
			return ((ISingleResult<SP_OBTENER_DATOS_ORDEN_SERVICIOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_DATOS_OS_AREA")]
		public ISingleResult<SP_OBTENER_DATOS_OS_AREAResult> SP_OBTENER_DATOS_OS_AREA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDEMPRESA", DbType="VarChar(5)")] string iDEMPRESA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NROORDEN", DbType="VarChar(10)")] string nROORDEN)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDEMPRESA, nROORDEN);
			return ((ISingleResult<SP_OBTENER_DATOS_OS_AREAResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_DATOS_OS_CONTRATA")]
		public ISingleResult<SP_OBTENER_DATOS_OS_CONTRATAResult> SP_OBTENER_DATOS_OS_CONTRATA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDEMPRESA", DbType="VarChar(5)")] string iDEMPRESA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NROORDEN", DbType="VarChar(10)")] string nROORDEN)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDEMPRESA, nROORDEN);
			return ((ISingleResult<SP_OBTENER_DATOS_OS_CONTRATAResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_DATOS_OS_SEDE")]
		public ISingleResult<SP_OBTENER_DATOS_OS_SEDEResult> SP_OBTENER_DATOS_OS_SEDE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDEMPRESA", DbType="VarChar(5)")] string iDEMPRESA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NROORDEN", DbType="VarChar(10)")] string nROORDEN)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDEMPRESA, nROORDEN);
			return ((ISingleResult<SP_OBTENER_DATOS_OS_SEDEResult>)(result.ReturnValue));
		}

        [global::System.Data.Linq.Mapping.FunctionAttribute(Name = "dbo.SP_MANT_REG_ORDEN_SERVICIO")]
        public int SP_MANT_REG_ORDEN_SERVICIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "Opcion", DbType = "Int")] System.Nullable<int> opcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "IdEmpresa", DbType = "VarChar(5)")] string idEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "NroOrden", DbType = "Char(10)")] string nroOrden, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "Descripcion", DbType = "VarChar(30)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "FechaRealInicio", DbType = "DateTime")] System.Nullable<System.DateTime> fechaRealInicio, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "FechaRealFin", DbType = "DateTime")] System.Nullable<System.DateTime> fechaRealFin, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "FechaControlInicio", DbType = "DateTime")] System.Nullable<System.DateTime> fechaControlInicio, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "FechaControlFin", DbType = "DateTime")] System.Nullable<System.DateTime> fechaControlFin, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "Usuario", DbType = "VarChar(50)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "RETURN_VALUE", DbType = "Bit")] ref System.Nullable<bool> RETURN_VALUE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "NroOrdenRetorno", DbType = "Char(10)")] ref string nroOrdenRetorno)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), opcion, idEmpresa, nroOrden, descripcion, fechaRealInicio, fechaRealFin, fechaControlInicio, fechaControlFin, usuario, RETURN_VALUE, nroOrdenRetorno);
            RETURN_VALUE = ((System.Nullable<bool>)(result.GetParameterValue(9)));
            nroOrdenRetorno = ((string)(result.GetParameterValue(10)));
            return ((int)(result.ReturnValue));
        }

        [global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_LISTAR_PERIODOS_GENERADOS")]
		public ISingleResult<SP_LISTAR_PERIODOS_GENERADOSResult> SP_LISTAR_PERIODOS_GENERADOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NroOrden", DbType="VarChar(10)")] string nroOrden, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contratista", DbType="VarChar(5)")] string contratista, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cliente", DbType="VarChar(5)")] string cliente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mes", DbType="Char(2)")] string mes, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Anho", DbType="Char(4)")] string anho)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nroOrden, contratista, cliente, mes, anho);
			return ((ISingleResult<SP_LISTAR_PERIODOS_GENERADOSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_LISTAR_ORDENES_SERVICIO")]
		public ISingleResult<SP_LISTAR_ORDENES_SERVICIOResult> SP_LISTAR_ORDENES_SERVICIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NroOrden", DbType="VarChar(10)")] string nroOrden, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contratista", DbType="VarChar(5)")] string contratista, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cliente", DbType="VarChar(5)")] string cliente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaDesde", DbType="DateTime")] System.Nullable<System.DateTime> fechaDesde, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaHasta", DbType="DateTime")] System.Nullable<System.DateTime> fechaHasta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="VarChar(10)")] string idUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nroOrden, contratista, cliente, fechaDesde, fechaHasta, idUsuario);
			return ((ISingleResult<SP_LISTAR_ORDENES_SERVICIOResult>)(result.ReturnValue));
		}

        [global::System.Data.Linq.Mapping.FunctionAttribute(Name = "dbo.SP_GEN_DOCUMENTACION_MENSUAL")]
        public int SP_GEN_DOCUMENTACION_MENSUAL([global::System.Data.Linq.Mapping.ParameterAttribute(Name = "IdEmpresa", DbType = "VarChar(5)")] string idEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "NroOrden", DbType = "VarChar(10)")] string nroOrden, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "MesVigente", DbType = "VarChar(2)")] string mesVigente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "AnhoVigente", DbType = "VarChar(4)")] string anhoVigente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "RegistradoPor", DbType = "VarChar(50)")] string registradoPor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "RETURN_VALUE", DbType = "Bit")] ref System.Nullable<bool> RETURN_VALUE)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idEmpresa, nroOrden, mesVigente, anhoVigente, registradoPor, RETURN_VALUE);
            RETURN_VALUE = ((System.Nullable<bool>)(result.GetParameterValue(5)));
            return ((int)(result.ReturnValue));
        }

        [global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_DEL_DOCUMENTACION_MENSUAL")]
		public int SP_DEL_DOCUMENTACION_MENSUAL([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contratista", DbType="VarChar(5)")] string contratista, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NroOrden", DbType="VarChar(10)")] string nroOrden, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cliente", DbType="VarChar(5)")] string cliente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mes", DbType="Char(2)")] string mes, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Anho", DbType="Char(4)")] string anho, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "RETURN_VALUE", DbType = "Bit")] ref System.Nullable<bool> RETURN_VALUE)
        {
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), contratista, nroOrden, cliente, mes, anho, RETURN_VALUE);
            RETURN_VALUE = ((System.Nullable<bool>)(result.GetParameterValue(5)));
            return ((int)(result.ReturnValue));
		}
	}
	
	public partial class SP_LISTAR_CONTRATASResult
	{
		
		private string _IDEMPRESA;
		
		private string _RAZONSOCIAL;
		
		public SP_LISTAR_CONTRATASResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDEMPRESA", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IDEMPRESA
		{
			get
			{
				return this._IDEMPRESA;
			}
			set
			{
				if ((this._IDEMPRESA != value))
				{
					this._IDEMPRESA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RAZONSOCIAL", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string RAZONSOCIAL
		{
			get
			{
				return this._RAZONSOCIAL;
			}
			set
			{
				if ((this._RAZONSOCIAL != value))
				{
					this._RAZONSOCIAL = value;
				}
			}
		}
	}
	
	public partial class SP_LISTAR_ORDENESResult
	{
		
		private string _NroOrden;
		
		private string _CodigoCliente;
		
		private string _Cliente;
		
		private string _CodigoContratista;
		
		private string _Contratista;
		
		private string _CodigoSubContratista;
		
		private string _SubContratista;
		
		private string _Usuario;
		
		private System.Nullable<System.DateTime> _FechaControlInicio;
		
		private System.Nullable<System.DateTime> _FechaControlFin;
		
		private System.Nullable<System.DateTime> _FechaMovimiento;
		
		private char _Estado;
		
		public SP_LISTAR_ORDENESResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NroOrden", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string NroOrden
		{
			get
			{
				return this._NroOrden;
			}
			set
			{
				if ((this._NroOrden != value))
				{
					this._NroOrden = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoCliente", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string CodigoCliente
		{
			get
			{
				return this._CodigoCliente;
			}
			set
			{
				if ((this._CodigoCliente != value))
				{
					this._CodigoCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cliente", DbType="VarChar(50)")]
		public string Cliente
		{
			get
			{
				return this._Cliente;
			}
			set
			{
				if ((this._Cliente != value))
				{
					this._Cliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoContratista", DbType="VarChar(5)")]
		public string CodigoContratista
		{
			get
			{
				return this._CodigoContratista;
			}
			set
			{
				if ((this._CodigoContratista != value))
				{
					this._CodigoContratista = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contratista", DbType="VarChar(50)")]
		public string Contratista
		{
			get
			{
				return this._Contratista;
			}
			set
			{
				if ((this._Contratista != value))
				{
					this._Contratista = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoSubContratista", DbType="VarChar(5)")]
		public string CodigoSubContratista
		{
			get
			{
				return this._CodigoSubContratista;
			}
			set
			{
				if ((this._CodigoSubContratista != value))
				{
					this._CodigoSubContratista = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubContratista", DbType="VarChar(50)")]
		public string SubContratista
		{
			get
			{
				return this._SubContratista;
			}
			set
			{
				if ((this._SubContratista != value))
				{
					this._SubContratista = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this._Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaControlInicio", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaControlInicio
		{
			get
			{
				return this._FechaControlInicio;
			}
			set
			{
				if ((this._FechaControlInicio != value))
				{
					this._FechaControlInicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaControlFin", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaControlFin
		{
			get
			{
				return this._FechaControlFin;
			}
			set
			{
				if ((this._FechaControlFin != value))
				{
					this._FechaControlFin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaMovimiento", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaMovimiento
		{
			get
			{
				return this._FechaMovimiento;
			}
			set
			{
				if ((this._FechaMovimiento != value))
				{
					this._FechaMovimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Char(1) NOT NULL")]
		public char Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_DATOS_ORDEN_SERVICIOResult
	{
		
		private string _IdEmpresa;
		
		private string _NroOrden;
		
		private string _Descripcion;
		
		private System.Nullable<System.DateTime> _FechaRealInicio;
		
		private System.Nullable<System.DateTime> _FechaRealFin;
		
		private System.Nullable<System.DateTime> _FechaControlInicio;
		
		private System.Nullable<System.DateTime> _FechaControlFin;
		
		private char _Estado;
		
		private System.Nullable<System.DateTime> _FechaProceso;
		
		private string _HoraProceso;
		
		private string _ProcesadoPor;
		
		private System.Nullable<System.DateTime> _FechaCierre;
		
		private string _HoraCierre;
		
		private string _CerradoPor;
		
		private System.Nullable<System.DateTime> _FechaRegistro;
		
		private string _HoraRegistro;
		
		private string _RegistradoPor;
		
		public SP_OBTENER_DATOS_ORDEN_SERVICIOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEmpresa", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IdEmpresa
		{
			get
			{
				return this._IdEmpresa;
			}
			set
			{
				if ((this._IdEmpresa != value))
				{
					this._IdEmpresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NroOrden", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string NroOrden
		{
			get
			{
				return this._NroOrden;
			}
			set
			{
				if ((this._NroOrden != value))
				{
					this._NroOrden = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRealInicio", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaRealInicio
		{
			get
			{
				return this._FechaRealInicio;
			}
			set
			{
				if ((this._FechaRealInicio != value))
				{
					this._FechaRealInicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRealFin", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaRealFin
		{
			get
			{
				return this._FechaRealFin;
			}
			set
			{
				if ((this._FechaRealFin != value))
				{
					this._FechaRealFin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaControlInicio", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaControlInicio
		{
			get
			{
				return this._FechaControlInicio;
			}
			set
			{
				if ((this._FechaControlInicio != value))
				{
					this._FechaControlInicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaControlFin", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaControlFin
		{
			get
			{
				return this._FechaControlFin;
			}
			set
			{
				if ((this._FechaControlFin != value))
				{
					this._FechaControlFin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Char(1) NOT NULL")]
		public char Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaProceso", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaProceso
		{
			get
			{
				return this._FechaProceso;
			}
			set
			{
				if ((this._FechaProceso != value))
				{
					this._FechaProceso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoraProceso", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string HoraProceso
		{
			get
			{
				return this._HoraProceso;
			}
			set
			{
				if ((this._HoraProceso != value))
				{
					this._HoraProceso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProcesadoPor", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string ProcesadoPor
		{
			get
			{
				return this._ProcesadoPor;
			}
			set
			{
				if ((this._ProcesadoPor != value))
				{
					this._ProcesadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCierre", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaCierre
		{
			get
			{
				return this._FechaCierre;
			}
			set
			{
				if ((this._FechaCierre != value))
				{
					this._FechaCierre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoraCierre", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string HoraCierre
		{
			get
			{
				return this._HoraCierre;
			}
			set
			{
				if ((this._HoraCierre != value))
				{
					this._HoraCierre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CerradoPor", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string CerradoPor
		{
			get
			{
				return this._CerradoPor;
			}
			set
			{
				if ((this._CerradoPor != value))
				{
					this._CerradoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRegistro", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaRegistro
		{
			get
			{
				return this._FechaRegistro;
			}
			set
			{
				if ((this._FechaRegistro != value))
				{
					this._FechaRegistro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoraRegistro", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string HoraRegistro
		{
			get
			{
				return this._HoraRegistro;
			}
			set
			{
				if ((this._HoraRegistro != value))
				{
					this._HoraRegistro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegistradoPor", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string RegistradoPor
		{
			get
			{
				return this._RegistradoPor;
			}
			set
			{
				if ((this._RegistradoPor != value))
				{
					this._RegistradoPor = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_DATOS_OS_AREAResult
	{
		
		private string _IdEmpresa;
		
		private string _NroOrden;
		
		private string _CodigoDpto;
		
		private string _NombreDpto;
		
		public SP_OBTENER_DATOS_OS_AREAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEmpresa", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IdEmpresa
		{
			get
			{
				return this._IdEmpresa;
			}
			set
			{
				if ((this._IdEmpresa != value))
				{
					this._IdEmpresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NroOrden", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string NroOrden
		{
			get
			{
				return this._NroOrden;
			}
			set
			{
				if ((this._NroOrden != value))
				{
					this._NroOrden = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoDpto", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string CodigoDpto
		{
			get
			{
				return this._CodigoDpto;
			}
			set
			{
				if ((this._CodigoDpto != value))
				{
					this._CodigoDpto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreDpto", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string NombreDpto
		{
			get
			{
				return this._NombreDpto;
			}
			set
			{
				if ((this._NombreDpto != value))
				{
					this._NombreDpto = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_DATOS_OS_CONTRATAResult
	{
		
		private string _IdEmpresa;
		
		private string _NroOrden;
		
		private string _IdContrata;
		
		private string _Contrata;
		
		private string _IdSubContrata;
		
		private string _SubContrata;
		
		public SP_OBTENER_DATOS_OS_CONTRATAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEmpresa", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IdEmpresa
		{
			get
			{
				return this._IdEmpresa;
			}
			set
			{
				if ((this._IdEmpresa != value))
				{
					this._IdEmpresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NroOrden", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string NroOrden
		{
			get
			{
				return this._NroOrden;
			}
			set
			{
				if ((this._NroOrden != value))
				{
					this._NroOrden = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdContrata", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IdContrata
		{
			get
			{
				return this._IdContrata;
			}
			set
			{
				if ((this._IdContrata != value))
				{
					this._IdContrata = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contrata", DbType="VarChar(50)")]
		public string Contrata
		{
			get
			{
				return this._Contrata;
			}
			set
			{
				if ((this._Contrata != value))
				{
					this._Contrata = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSubContrata", DbType="VarChar(5)")]
		public string IdSubContrata
		{
			get
			{
				return this._IdSubContrata;
			}
			set
			{
				if ((this._IdSubContrata != value))
				{
					this._IdSubContrata = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubContrata", DbType="VarChar(50)")]
		public string SubContrata
		{
			get
			{
				return this._SubContrata;
			}
			set
			{
				if ((this._SubContrata != value))
				{
					this._SubContrata = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_DATOS_OS_SEDEResult
	{
		
		private string _IdEmpresa;
		
		private string _NroOrden;
		
		private string _CodigoSede;
		
		private string _DescripcionSede;
		
		public SP_OBTENER_DATOS_OS_SEDEResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEmpresa", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IdEmpresa
		{
			get
			{
				return this._IdEmpresa;
			}
			set
			{
				if ((this._IdEmpresa != value))
				{
					this._IdEmpresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NroOrden", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string NroOrden
		{
			get
			{
				return this._NroOrden;
			}
			set
			{
				if ((this._NroOrden != value))
				{
					this._NroOrden = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoSede", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string CodigoSede
		{
			get
			{
				return this._CodigoSede;
			}
			set
			{
				if ((this._CodigoSede != value))
				{
					this._CodigoSede = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescripcionSede", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string DescripcionSede
		{
			get
			{
				return this._DescripcionSede;
			}
			set
			{
				if ((this._DescripcionSede != value))
				{
					this._DescripcionSede = value;
				}
			}
		}
	}
	
	public partial class SP_LISTAR_PERIODOS_GENERADOSResult
	{
		
		private string _Cliente;
		
		private string _NroOrden;
		
		private string _Contratista;
		
		private string _Mes;
		
		private string _NombreMes;
		
		private string _Año;
		
		private System.Nullable<char> _Estado;
		
		private string _Situacion;
		
		private string _EsContratista;
		
		private System.Nullable<int> _Empleados;
		
		private System.Nullable<int> _Vehiculos;
		
		private System.Nullable<int> _Web;
		
		public SP_LISTAR_PERIODOS_GENERADOSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cliente", DbType="VarChar(5)")]
		public string Cliente
		{
			get
			{
				return this._Cliente;
			}
			set
			{
				if ((this._Cliente != value))
				{
					this._Cliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NroOrden", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string NroOrden
		{
			get
			{
				return this._NroOrden;
			}
			set
			{
				if ((this._NroOrden != value))
				{
					this._NroOrden = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contratista", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string Contratista
		{
			get
			{
				return this._Contratista;
			}
			set
			{
				if ((this._Contratista != value))
				{
					this._Contratista = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mes", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string Mes
		{
			get
			{
				return this._Mes;
			}
			set
			{
				if ((this._Mes != value))
				{
					this._Mes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreMes", DbType="VarChar(20)")]
		public string NombreMes
		{
			get
			{
				return this._NombreMes;
			}
			set
			{
				if ((this._NombreMes != value))
				{
					this._NombreMes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Año", DbType="Char(4)")]
		public string Año
		{
			get
			{
				return this._Año;
			}
			set
			{
				if ((this._Año != value))
				{
					this._Año = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Char(1)")]
		public System.Nullable<char> Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Situacion", DbType="VarChar(100)")]
		public string Situacion
		{
			get
			{
				return this._Situacion;
			}
			set
			{
				if ((this._Situacion != value))
				{
					this._Situacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EsContratista", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string EsContratista
		{
			get
			{
				return this._EsContratista;
			}
			set
			{
				if ((this._EsContratista != value))
				{
					this._EsContratista = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Empleados", DbType="Int")]
		public System.Nullable<int> Empleados
		{
			get
			{
				return this._Empleados;
			}
			set
			{
				if ((this._Empleados != value))
				{
					this._Empleados = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vehiculos", DbType="Int")]
		public System.Nullable<int> Vehiculos
		{
			get
			{
				return this._Vehiculos;
			}
			set
			{
				if ((this._Vehiculos != value))
				{
					this._Vehiculos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Web", DbType="Int")]
		public System.Nullable<int> Web
		{
			get
			{
				return this._Web;
			}
			set
			{
				if ((this._Web != value))
				{
					this._Web = value;
				}
			}
		}
	}
	
	public partial class SP_LISTAR_ORDENES_SERVICIOResult
	{
		
		private string _NroOrden;
		
		private string _CodigoCliente;
		
		private string _Cliente;
		
		private string _CodigoContratista;
		
		private string _Contratista;
		
		private string _CodigoSubContratista;
		
		private string _SubContratista;
		
		private string _Usuario;
		
		private System.Nullable<System.DateTime> _FechaControlInicio;
		
		private System.Nullable<System.DateTime> _FechaControlFin;
		
		private System.Nullable<System.DateTime> _FechaMovimiento;
		
		private char _Estado;
		
		public SP_LISTAR_ORDENES_SERVICIOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NroOrden", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string NroOrden
		{
			get
			{
				return this._NroOrden;
			}
			set
			{
				if ((this._NroOrden != value))
				{
					this._NroOrden = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoCliente", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string CodigoCliente
		{
			get
			{
				return this._CodigoCliente;
			}
			set
			{
				if ((this._CodigoCliente != value))
				{
					this._CodigoCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cliente", DbType="VarChar(50)")]
		public string Cliente
		{
			get
			{
				return this._Cliente;
			}
			set
			{
				if ((this._Cliente != value))
				{
					this._Cliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoContratista", DbType="VarChar(5)")]
		public string CodigoContratista
		{
			get
			{
				return this._CodigoContratista;
			}
			set
			{
				if ((this._CodigoContratista != value))
				{
					this._CodigoContratista = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contratista", DbType="VarChar(50)")]
		public string Contratista
		{
			get
			{
				return this._Contratista;
			}
			set
			{
				if ((this._Contratista != value))
				{
					this._Contratista = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoSubContratista", DbType="VarChar(5)")]
		public string CodigoSubContratista
		{
			get
			{
				return this._CodigoSubContratista;
			}
			set
			{
				if ((this._CodigoSubContratista != value))
				{
					this._CodigoSubContratista = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubContratista", DbType="VarChar(50)")]
		public string SubContratista
		{
			get
			{
				return this._SubContratista;
			}
			set
			{
				if ((this._SubContratista != value))
				{
					this._SubContratista = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this._Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaControlInicio", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaControlInicio
		{
			get
			{
				return this._FechaControlInicio;
			}
			set
			{
				if ((this._FechaControlInicio != value))
				{
					this._FechaControlInicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaControlFin", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaControlFin
		{
			get
			{
				return this._FechaControlFin;
			}
			set
			{
				if ((this._FechaControlFin != value))
				{
					this._FechaControlFin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaMovimiento", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaMovimiento
		{
			get
			{
				return this._FechaMovimiento;
			}
			set
			{
				if ((this._FechaMovimiento != value))
				{
					this._FechaMovimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Char(1) NOT NULL")]
		public char Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
