#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siggo.SIGC.DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SiggoData")]
	public partial class DATipoDocumentoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DATipoDocumentoDataContext() : 
				base(global::Siggo.SIGC.DataAccess.Properties.Settings.Default.SiggoDataConnectionString3, mappingSource)
		{
			OnCreated();
		}
		
		public DATipoDocumentoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DATipoDocumentoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DATipoDocumentoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DATipoDocumentoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_MANT_REG_TIPO_DOCUMENTO")]
		public int SP_MANT_REG_TIPO_DOCUMENTO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Opcion", DbType="Int")] System.Nullable<int> opcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoDocumento", DbType="Int")] System.Nullable<int> idTipoDocumento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(50)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DescripcionLarga", DbType="VarChar(50)")] string descripcionLarga, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoServicio", DbType="Int")] System.Nullable<int> idTipoServicio, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoRiesgo", DbType="Int")] System.Nullable<int> idTipoRiesgo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NivelRiesgo", DbType="VarChar(20)")] string nivelRiesgo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RegistradoPor", DbType="VarChar(50)")] string registradoPor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "RETURN_VALUE", DbType = "Bit")] ref System.Nullable<bool> RETURN_VALUE)
        {
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), opcion, idTipoDocumento, descripcion, descripcionLarga, idTipoServicio, idTipoRiesgo, nivelRiesgo, registradoPor, RETURN_VALUE);
            RETURN_VALUE = ((System.Nullable<bool>)(result.GetParameterValue(8)));

            return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_DATOS_TIPO_DOCUMENTO")]
		public ISingleResult<SP_OBTENER_DATOS_TIPO_DOCUMENTOResult> SP_OBTENER_DATOS_TIPO_DOCUMENTO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoDocumento", DbType="Int")] System.Nullable<int> idTipoDocumento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoServicio", DbType="Int")] System.Nullable<int> idTipoServicio)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idTipoDocumento, idTipoServicio);
			return ((ISingleResult<SP_OBTENER_DATOS_TIPO_DOCUMENTOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_LISTAR_TIPOS_DOCUMENTOS")]
		public ISingleResult<SP_LISTAR_TIPOS_DOCUMENTOSResult> SP_LISTAR_TIPOS_DOCUMENTOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Identificador", DbType="VarChar(5)")] string identificador, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(100)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoServicio", DbType="VarChar(5)")] string idTipoServicio)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), identificador, descripcion, idTipoServicio);
			return ((ISingleResult<SP_LISTAR_TIPOS_DOCUMENTOSResult>)(result.ReturnValue));
		}
	}
	
	public partial class SP_OBTENER_DATOS_TIPO_DOCUMENTOResult
	{
		
		private int _IdTipoDocumento;
		
		private string _Descripcion;
		
		private string _DescripcionLarga;
		
		private int _IdTipoServicio;
		
		private int _IdTipoRiesgo;
		
		private string _NivelRiesgo;
		
		private char _Estado;
		
		private char _Accion;
		
		private string _FECMAKER;
		
		private string _HoraRegistro;
		
		private string _MAKER;
		
		public SP_OBTENER_DATOS_TIPO_DOCUMENTOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoDocumento", DbType="Int NOT NULL")]
		public int IdTipoDocumento
		{
			get
			{
				return this._IdTipoDocumento;
			}
			set
			{
				if ((this._IdTipoDocumento != value))
				{
					this._IdTipoDocumento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescripcionLarga", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DescripcionLarga
		{
			get
			{
				return this._DescripcionLarga;
			}
			set
			{
				if ((this._DescripcionLarga != value))
				{
					this._DescripcionLarga = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoServicio", DbType="Int NOT NULL")]
		public int IdTipoServicio
		{
			get
			{
				return this._IdTipoServicio;
			}
			set
			{
				if ((this._IdTipoServicio != value))
				{
					this._IdTipoServicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoRiesgo", DbType="Int NOT NULL")]
		public int IdTipoRiesgo
		{
			get
			{
				return this._IdTipoRiesgo;
			}
			set
			{
				if ((this._IdTipoRiesgo != value))
				{
					this._IdTipoRiesgo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NivelRiesgo", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NivelRiesgo
		{
			get
			{
				return this._NivelRiesgo;
			}
			set
			{
				if ((this._NivelRiesgo != value))
				{
					this._NivelRiesgo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Char(1) NOT NULL")]
		public char Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Accion", DbType="Char(1) NOT NULL")]
		public char Accion
		{
			get
			{
				return this._Accion;
			}
			set
			{
				if ((this._Accion != value))
				{
					this._Accion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECMAKER", DbType="VarChar(30)")]
		public string FECMAKER
		{
			get
			{
				return this._FECMAKER;
			}
			set
			{
				if ((this._FECMAKER != value))
				{
					this._FECMAKER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoraRegistro", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string HoraRegistro
		{
			get
			{
				return this._HoraRegistro;
			}
			set
			{
				if ((this._HoraRegistro != value))
				{
					this._HoraRegistro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKER", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MAKER
		{
			get
			{
				return this._MAKER;
			}
			set
			{
				if ((this._MAKER != value))
				{
					this._MAKER = value;
				}
			}
		}
	}
	
	public partial class SP_LISTAR_TIPOS_DOCUMENTOSResult
	{
		
		private int _IdTipoDocumento;
		
		private string _Descripcion;
		
		private string _DescripcionLarga;
		
		private int _IdTipoRiesgo;
		
		private string _TipoRiesgo;
		
		private string _NivelRiesgo;
		
		private string _DescNivelRiesgo;
		
		private int _IdTipoServicio;
		
		private string _Servicio;
		
		private char _ESTADO;
		
		private char _ACCION;
		
		private System.DateTime _FECHAREGISTRO;
		
		private string _HORAREGISTRO;
		
		private string _REGISTRADOPOR;
		
		public SP_LISTAR_TIPOS_DOCUMENTOSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoDocumento", DbType="Int NOT NULL")]
		public int IdTipoDocumento
		{
			get
			{
				return this._IdTipoDocumento;
			}
			set
			{
				if ((this._IdTipoDocumento != value))
				{
					this._IdTipoDocumento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescripcionLarga", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DescripcionLarga
		{
			get
			{
				return this._DescripcionLarga;
			}
			set
			{
				if ((this._DescripcionLarga != value))
				{
					this._DescripcionLarga = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoRiesgo", DbType="Int NOT NULL")]
		public int IdTipoRiesgo
		{
			get
			{
				return this._IdTipoRiesgo;
			}
			set
			{
				if ((this._IdTipoRiesgo != value))
				{
					this._IdTipoRiesgo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoRiesgo", DbType="VarChar(100)")]
		public string TipoRiesgo
		{
			get
			{
				return this._TipoRiesgo;
			}
			set
			{
				if ((this._TipoRiesgo != value))
				{
					this._TipoRiesgo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NivelRiesgo", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NivelRiesgo
		{
			get
			{
				return this._NivelRiesgo;
			}
			set
			{
				if ((this._NivelRiesgo != value))
				{
					this._NivelRiesgo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescNivelRiesgo", DbType="VarChar(100)")]
		public string DescNivelRiesgo
		{
			get
			{
				return this._DescNivelRiesgo;
			}
			set
			{
				if ((this._DescNivelRiesgo != value))
				{
					this._DescNivelRiesgo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoServicio", DbType="Int NOT NULL")]
		public int IdTipoServicio
		{
			get
			{
				return this._IdTipoServicio;
			}
			set
			{
				if ((this._IdTipoServicio != value))
				{
					this._IdTipoServicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Servicio", DbType="VarChar(50)")]
		public string Servicio
		{
			get
			{
				return this._Servicio;
			}
			set
			{
				if ((this._Servicio != value))
				{
					this._Servicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="Char(1) NOT NULL")]
		public char ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCION", DbType="Char(1) NOT NULL")]
		public char ACCION
		{
			get
			{
				return this._ACCION;
			}
			set
			{
				if ((this._ACCION != value))
				{
					this._ACCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHAREGISTRO", DbType="DateTime NOT NULL")]
		public System.DateTime FECHAREGISTRO
		{
			get
			{
				return this._FECHAREGISTRO;
			}
			set
			{
				if ((this._FECHAREGISTRO != value))
				{
					this._FECHAREGISTRO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HORAREGISTRO", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string HORAREGISTRO
		{
			get
			{
				return this._HORAREGISTRO;
			}
			set
			{
				if ((this._HORAREGISTRO != value))
				{
					this._HORAREGISTRO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REGISTRADOPOR", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string REGISTRADOPOR
		{
			get
			{
				return this._REGISTRADOPOR;
			}
			set
			{
				if ((this._REGISTRADOPOR != value))
				{
					this._REGISTRADOPOR = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
