#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siggo.SIGC.DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SiggoData")]
	public partial class DATipoServicioDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DATipoServicioDataContext() : 
				base(global::Siggo.SIGC.DataAccess.Properties.Settings.Default.SiggoDataConnectionString3, mappingSource)
		{
			OnCreated();
		}
		
		public DATipoServicioDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DATipoServicioDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DATipoServicioDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DATipoServicioDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_MANT_REG_TIPO_SERVICIO")]
		public int SP_MANT_REG_TIPO_SERVICIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Opcion", DbType="Int")] System.Nullable<int> opcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoServicio", DbType="Int")] System.Nullable<int> idTipoServicio, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(50)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RegistradoPor", DbType="VarChar(50)")] string registradoPor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "RETURN_VALUE", DbType = "Bit")] ref System.Nullable<bool> RETURN_VALUE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), opcion, idTipoServicio, descripcion, registradoPor, RETURN_VALUE);
            RETURN_VALUE = ((System.Nullable<bool>)(result.GetParameterValue(4)));
            return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_LISTAR_TIPO_SERVICIO")]
		public ISingleResult<SP_LISTAR_TIPO_SERVICIOResult> SP_LISTAR_TIPO_SERVICIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Identificador", DbType="VarChar(5)")] string identificador, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(100)")] string descripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), identificador, descripcion);
			return ((ISingleResult<SP_LISTAR_TIPO_SERVICIOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_TIPO_DOCUMENTOS_SERVICIO")]
		public ISingleResult<SP_OBTENER_TIPO_DOCUMENTOS_SERVICIOResult> SP_OBTENER_TIPO_DOCUMENTOS_SERVICIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoServicio", DbType="Int")] System.Nullable<int> idTipoServicio)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idTipoServicio);
			return ((ISingleResult<SP_OBTENER_TIPO_DOCUMENTOS_SERVICIOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_DATOS_TIPO_SERVICIO")]
		public ISingleResult<SP_OBTENER_DATOS_TIPO_SERVICIOResult> SP_OBTENER_DATOS_TIPO_SERVICIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDTIPOSERVICIO", DbType="VarChar(5)")] string iDTIPOSERVICIO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDTIPOSERVICIO);
			return ((ISingleResult<SP_OBTENER_DATOS_TIPO_SERVICIOResult>)(result.ReturnValue));
		}
	}
	
	public partial class SP_LISTAR_TIPO_SERVICIOResult
	{
		
		private int _IdTipoServicio;
		
		private string _Descripcion;
		
		private char _Estado;
		
		private char _Accion;
		
		private System.DateTime _FechaRegistro;
		
		private string _HoraRegistro;
		
		private string _RegistradoPor;
		
		public SP_LISTAR_TIPO_SERVICIOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoServicio", DbType="Int NOT NULL")]
		public int IdTipoServicio
		{
			get
			{
				return this._IdTipoServicio;
			}
			set
			{
				if ((this._IdTipoServicio != value))
				{
					this._IdTipoServicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Char(1) NOT NULL")]
		public char Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Accion", DbType="Char(1) NOT NULL")]
		public char Accion
		{
			get
			{
				return this._Accion;
			}
			set
			{
				if ((this._Accion != value))
				{
					this._Accion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRegistro", DbType="DateTime NOT NULL")]
		public System.DateTime FechaRegistro
		{
			get
			{
				return this._FechaRegistro;
			}
			set
			{
				if ((this._FechaRegistro != value))
				{
					this._FechaRegistro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoraRegistro", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string HoraRegistro
		{
			get
			{
				return this._HoraRegistro;
			}
			set
			{
				if ((this._HoraRegistro != value))
				{
					this._HoraRegistro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegistradoPor", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string RegistradoPor
		{
			get
			{
				return this._RegistradoPor;
			}
			set
			{
				if ((this._RegistradoPor != value))
				{
					this._RegistradoPor = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_TIPO_DOCUMENTOS_SERVICIOResult
	{
		
		private int _Codigo;
		
		private string _Descripcion;
		
		public SP_OBTENER_TIPO_DOCUMENTOS_SERVICIOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="Int NOT NULL")]
		public int Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this._Codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_DATOS_TIPO_SERVICIOResult
	{
		
		private int _IdTipoServicio;
		
		private string _Descripcion;
		
		private char _Estado;
		
		private char _Accion;
		
		private string _FECMAKER;
		
		private string _HoraRegistro;
		
		private string _MAKER;
		
		public SP_OBTENER_DATOS_TIPO_SERVICIOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoServicio", DbType="Int NOT NULL")]
		public int IdTipoServicio
		{
			get
			{
				return this._IdTipoServicio;
			}
			set
			{
				if ((this._IdTipoServicio != value))
				{
					this._IdTipoServicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Char(1) NOT NULL")]
		public char Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Accion", DbType="Char(1) NOT NULL")]
		public char Accion
		{
			get
			{
				return this._Accion;
			}
			set
			{
				if ((this._Accion != value))
				{
					this._Accion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECMAKER", DbType="VarChar(30)")]
		public string FECMAKER
		{
			get
			{
				return this._FECMAKER;
			}
			set
			{
				if ((this._FECMAKER != value))
				{
					this._FECMAKER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoraRegistro", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string HoraRegistro
		{
			get
			{
				return this._HoraRegistro;
			}
			set
			{
				if ((this._HoraRegistro != value))
				{
					this._HoraRegistro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKER", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MAKER
		{
			get
			{
				return this._MAKER;
			}
			set
			{
				if ((this._MAKER != value))
				{
					this._MAKER = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
