#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siggo.SIGC.DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SiggoData")]
	public partial class DAUsuarioWebDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DAUsuarioWebDataContext() : 
				base(global::Siggo.SIGC.DataAccess.Properties.Settings.Default.SiggoDataConnectionString3, mappingSource)
		{
			OnCreated();
		}
		
		public DAUsuarioWebDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DAUsuarioWebDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DAUsuarioWebDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DAUsuarioWebDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_EMPRESA_USUARIO")]
		public ISingleResult<SP_OBTENER_EMPRESA_USUARIOResult> SP_OBTENER_EMPRESA_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDUSUARIO", DbType="VarChar(5)")] string iDUSUARIO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDUSUARIO);
			return ((ISingleResult<SP_OBTENER_EMPRESA_USUARIOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_MANT_REG_USUARIOWEB")]
		public int SP_MANT_REG_USUARIOWEB([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Opcion", DbType="Int")] System.Nullable<int> opcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdEmpresa", DbType="VarChar(5)")] string idEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="VarChar(10)")] string idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreUsuario", DbType="VarChar(40)")] string nombreUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ApePaterno", DbType="VarChar(60)")] string apePaterno, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ApeMaterno", DbType="VarChar(60)")] string apeMaterno, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correo", DbType="VarChar(50)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contrasenha", DbType="VarChar(50)")] string contrasenha, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdRol", DbType="Int")] System.Nullable<int> idRol, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaAsignacion", DbType="DateTime")] System.Nullable<System.DateTime> fechaAsignacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EsUsuarioSiggo", DbType="Bit")] System.Nullable<bool> esUsuarioSiggo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RecibeNotificacion", DbType="Char(1)")] System.Nullable<char> recibeNotificacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RegistradoPor", DbType="VarChar(50)")] string registradoPor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), opcion, idEmpresa, idUsuario, nombreUsuario, apePaterno, apeMaterno, correo, contrasenha, idRol, fechaAsignacion, esUsuarioSiggo, recibeNotificacion, registradoPor);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_USUARIO_WEB")]
		public ISingleResult<SP_OBTENER_USUARIO_WEBResult> SP_OBTENER_USUARIO_WEB([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDUSUARIO", DbType="VarChar(5)")] string iDUSUARIO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDUSUARIO);
			return ((ISingleResult<SP_OBTENER_USUARIO_WEBResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_LISTAR_USUARIOSWEB")]
		public ISingleResult<SP_LISTAR_USUARIOSWEBResult> SP_LISTAR_USUARIOSWEB([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdEmpresa", DbType="VarChar(5)")] string idEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Identificador", DbType="VarChar(10)")] string identificador, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreUsuario", DbType="VarChar(100)")] string nombreUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idEmpresa, identificador, nombreUsuario);
			return ((ISingleResult<SP_LISTAR_USUARIOSWEBResult>)(result.ReturnValue));
		}
	}
	
	public partial class SP_OBTENER_EMPRESA_USUARIOResult
	{
		
		private string _CODIGO;
		
		private string _DESCRIPCION;
		
		public SP_OBTENER_EMPRESA_USUARIOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO", DbType="VarChar(5)")]
		public string CODIGO
		{
			get
			{
				return this._CODIGO;
			}
			set
			{
				if ((this._CODIGO != value))
				{
					this._CODIGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="VarChar(60)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_USUARIO_WEBResult
	{
		
		private string _IDEMPRESA;
		
		private string _IDUSUARIO;
		
		private string _NOMBREUSUARIO;
		
		private string _ApellidoPaternoUsuario;
		
		private string _ApellidoMaternoUsuario;
		
		private string _CORREO;
		
		private string _CONTRASENHA;
		
		private int _IDROL;
		
		private System.Nullable<System.DateTime> _FECHAASIGNACION;
		
		private System.Nullable<bool> _ESUSUARIOSIGGO;
		
		private System.Nullable<char> _RECIBENOTIFICACIONES;
		
		private char _ESTADO;
		
		private char _ACCION;
		
		private string _MAKER;
		
		private string _FECMAKER;
		
		private string _HORAMAKER;
		
		public SP_OBTENER_USUARIO_WEBResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDEMPRESA", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IDEMPRESA
		{
			get
			{
				return this._IDEMPRESA;
			}
			set
			{
				if ((this._IDEMPRESA != value))
				{
					this._IDEMPRESA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDUSUARIO", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string IDUSUARIO
		{
			get
			{
				return this._IDUSUARIO;
			}
			set
			{
				if ((this._IDUSUARIO != value))
				{
					this._IDUSUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBREUSUARIO", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string NOMBREUSUARIO
		{
			get
			{
				return this._NOMBREUSUARIO;
			}
			set
			{
				if ((this._NOMBREUSUARIO != value))
				{
					this._NOMBREUSUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApellidoPaternoUsuario", DbType="VarChar(60)")]
		public string ApellidoPaternoUsuario
		{
			get
			{
				return this._ApellidoPaternoUsuario;
			}
			set
			{
				if ((this._ApellidoPaternoUsuario != value))
				{
					this._ApellidoPaternoUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApellidoMaternoUsuario", DbType="VarChar(60)")]
		public string ApellidoMaternoUsuario
		{
			get
			{
				return this._ApellidoMaternoUsuario;
			}
			set
			{
				if ((this._ApellidoMaternoUsuario != value))
				{
					this._ApellidoMaternoUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CORREO
		{
			get
			{
				return this._CORREO;
			}
			set
			{
				if ((this._CORREO != value))
				{
					this._CORREO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTRASENHA", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CONTRASENHA
		{
			get
			{
				return this._CONTRASENHA;
			}
			set
			{
				if ((this._CONTRASENHA != value))
				{
					this._CONTRASENHA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDROL", DbType="Int NOT NULL")]
		public int IDROL
		{
			get
			{
				return this._IDROL;
			}
			set
			{
				if ((this._IDROL != value))
				{
					this._IDROL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHAASIGNACION", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHAASIGNACION
		{
			get
			{
				return this._FECHAASIGNACION;
			}
			set
			{
				if ((this._FECHAASIGNACION != value))
				{
					this._FECHAASIGNACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESUSUARIOSIGGO", DbType="Bit")]
		public System.Nullable<bool> ESUSUARIOSIGGO
		{
			get
			{
				return this._ESUSUARIOSIGGO;
			}
			set
			{
				if ((this._ESUSUARIOSIGGO != value))
				{
					this._ESUSUARIOSIGGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECIBENOTIFICACIONES", DbType="Char(1)")]
		public System.Nullable<char> RECIBENOTIFICACIONES
		{
			get
			{
				return this._RECIBENOTIFICACIONES;
			}
			set
			{
				if ((this._RECIBENOTIFICACIONES != value))
				{
					this._RECIBENOTIFICACIONES = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="Char(1) NOT NULL")]
		public char ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCION", DbType="Char(1) NOT NULL")]
		public char ACCION
		{
			get
			{
				return this._ACCION;
			}
			set
			{
				if ((this._ACCION != value))
				{
					this._ACCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKER", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string MAKER
		{
			get
			{
				return this._MAKER;
			}
			set
			{
				if ((this._MAKER != value))
				{
					this._MAKER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECMAKER", DbType="VarChar(30)")]
		public string FECMAKER
		{
			get
			{
				return this._FECMAKER;
			}
			set
			{
				if ((this._FECMAKER != value))
				{
					this._FECMAKER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HORAMAKER", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string HORAMAKER
		{
			get
			{
				return this._HORAMAKER;
			}
			set
			{
				if ((this._HORAMAKER != value))
				{
					this._HORAMAKER = value;
				}
			}
		}
	}
	
	public partial class SP_LISTAR_USUARIOSWEBResult
	{
		
		private string _IdEmpresa;
		
		private string _RazonSocial;
		
		private string _TipoEmpresaSiggo;
		
		private string _IdUsuario;
		
		private string _NombreUsuario;
		
		private string _Correo;
		
		private string _Contrasenha;
		
		private int _IdRol;
		
		private string _DescripcionRol;
		
		private System.Nullable<System.DateTime> _FechaAsignacion;
		
		private System.Nullable<bool> _EsUsuarioSiggo;
		
		private System.Nullable<char> _RecibeNotificaciones;
		
		private char _ESTADO;
		
		private char _ACCION;
		
		private System.Nullable<System.DateTime> _FECHAREGISTRO;
		
		private string _HORAREGISTRO;
		
		private string _REGISTRADOPOR;
		
		public SP_LISTAR_USUARIOSWEBResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEmpresa", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IdEmpresa
		{
			get
			{
				return this._IdEmpresa;
			}
			set
			{
				if ((this._IdEmpresa != value))
				{
					this._IdEmpresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RazonSocial", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string RazonSocial
		{
			get
			{
				return this._RazonSocial;
			}
			set
			{
				if ((this._RazonSocial != value))
				{
					this._RazonSocial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoEmpresaSiggo", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string TipoEmpresaSiggo
		{
			get
			{
				return this._TipoEmpresaSiggo;
			}
			set
			{
				if ((this._TipoEmpresaSiggo != value))
				{
					this._TipoEmpresaSiggo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this._IdUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreUsuario", DbType="VarChar(162) NOT NULL", CanBeNull=false)]
		public string NombreUsuario
		{
			get
			{
				return this._NombreUsuario;
			}
			set
			{
				if ((this._NombreUsuario != value))
				{
					this._NombreUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this._Correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contrasenha", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Contrasenha
		{
			get
			{
				return this._Contrasenha;
			}
			set
			{
				if ((this._Contrasenha != value))
				{
					this._Contrasenha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRol", DbType="Int NOT NULL")]
		public int IdRol
		{
			get
			{
				return this._IdRol;
			}
			set
			{
				if ((this._IdRol != value))
				{
					this._IdRol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescripcionRol", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DescripcionRol
		{
			get
			{
				return this._DescripcionRol;
			}
			set
			{
				if ((this._DescripcionRol != value))
				{
					this._DescripcionRol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAsignacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaAsignacion
		{
			get
			{
				return this._FechaAsignacion;
			}
			set
			{
				if ((this._FechaAsignacion != value))
				{
					this._FechaAsignacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EsUsuarioSiggo", DbType="Bit")]
		public System.Nullable<bool> EsUsuarioSiggo
		{
			get
			{
				return this._EsUsuarioSiggo;
			}
			set
			{
				if ((this._EsUsuarioSiggo != value))
				{
					this._EsUsuarioSiggo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecibeNotificaciones", DbType="Char(1)")]
		public System.Nullable<char> RecibeNotificaciones
		{
			get
			{
				return this._RecibeNotificaciones;
			}
			set
			{
				if ((this._RecibeNotificaciones != value))
				{
					this._RecibeNotificaciones = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="Char(1) NOT NULL")]
		public char ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCION", DbType="Char(1) NOT NULL")]
		public char ACCION
		{
			get
			{
				return this._ACCION;
			}
			set
			{
				if ((this._ACCION != value))
				{
					this._ACCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHAREGISTRO", DbType="DateTime")]
		public System.Nullable<System.DateTime> FECHAREGISTRO
		{
			get
			{
				return this._FECHAREGISTRO;
			}
			set
			{
				if ((this._FECHAREGISTRO != value))
				{
					this._FECHAREGISTRO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HORAREGISTRO", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string HORAREGISTRO
		{
			get
			{
				return this._HORAREGISTRO;
			}
			set
			{
				if ((this._HORAREGISTRO != value))
				{
					this._HORAREGISTRO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REGISTRADOPOR", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string REGISTRADOPOR
		{
			get
			{
				return this._REGISTRADOPOR;
			}
			set
			{
				if ((this._REGISTRADOPOR != value))
				{
					this._REGISTRADOPOR = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
